//! Derived from `shatari-data/src/bonuses.php` and `src/items.php`, (c) Gerard
//! Dombroski, Apache-2.0. Ported to Rust; evaluates the generated DB2 rules in
//! process, limits item metadata to the curated catalogue, and never changes a
//! stored bonus-list market identity.
//!
//! The data is generated by `scripts/catalog-sync.py --generate-bonus-data`.
//! It is per-patch and embedded at build time; the collector and the runtime
//! Blizzard tooltip provider never fetch or depend on it.

use std::collections::BTreeMap;
use std::sync::OnceLock;

use serde::Deserialize;

use crate::item::ItemMetadata;

use super::{Copper, ItemId};

const EMBEDDED: &str = include_str!("bonus-data.json");
const PLAYER_LEVEL_CAP: i64 = 90;

/// The four tertiary stats represented by item bonus ids.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub enum TertiaryStat {
    Speed,
    Leech,
    Avoidance,
    Indestructible,
}

impl TertiaryStat {
    const ALL: [TertiaryStat; 4] = [
        TertiaryStat::Speed,
        TertiaryStat::Leech,
        TertiaryStat::Avoidance,
        TertiaryStat::Indestructible,
    ];

    const fn key(self) -> &'static str {
        match self {
            TertiaryStat::Speed => "speed",
            TertiaryStat::Leech => "leech",
            TertiaryStat::Avoidance => "avoidance",
            TertiaryStat::Indestructible => "indestructible",
        }
    }
}

/// Presentation facts calculated from an item's base DB2 record and its bonus
/// list. None is stored in price history: the bonus-list string remains the
/// stable market identity across a game patch renumbering.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct DecodedItem {
    pub item_level: u16,
    pub name_suffix: Option<String>,
    pub tertiary_stats: Vec<TertiaryStat>,
}

#[derive(Deserialize)]
struct Data {
    level_data: LevelData,
    suffixes: BTreeMap<String, (i64, i64)>,
    suffix_names: BTreeMap<String, String>,
    curve_points: BTreeMap<String, Vec<(f64, f64)>>,
    tertiary_stats: BTreeMap<String, Vec<u32>>,
    squish_eras: Vec<SquishEra>,
    items: BTreeMap<String, Item>,
}

#[derive(Deserialize)]
struct LevelData {
    legacy_adjust: BTreeMap<String, i64>,
    content_tuning: BTreeMap<String, [i64; 3]>,
    legacy_set: BTreeMap<String, [i64; 2]>,
    era_curve_set: BTreeMap<String, [i64; 3]>,
    item_scaling_set: BTreeMap<String, [i64; 5]>,
    item_scaling_set_by_player: BTreeMap<String, [i64; 5]>,
    era_adjust: BTreeMap<String, [i64; 3]>,
    adjust: BTreeMap<String, [i64; 2]>,
}

#[derive(Deserialize)]
struct SquishEra {
    id: i64,
    #[serde(default)]
    curve: Vec<(f64, f64)>,
    #[serde(default)]
    target: bool,
}

#[derive(Deserialize)]
struct Item {
    icon: Option<String>,
    vendor_buy: Option<u64>,
    vendor_sell: Option<u64>,
    stack_size: u32,
    bind_on_pickup: bool,
    expansion: Option<u8>,
    base_item_level: i64,
    squish_era: i64,
}

fn data() -> &'static Data {
    static DATA: OnceLock<Data> = OnceLock::new();
    DATA.get_or_init(|| serde_json::from_str(EMBEDDED).expect("embedded bonus data is malformed"))
}

fn id_key(id: u32) -> String {
    id.to_string()
}

fn rounded(value: f64) -> i64 {
    value.round() as i64
}

/// The piecewise-linear DB2 curve evaluator used by every scaling mechanism.
fn curve(data: &Data, curve_id: i64, x: i64) -> f64 {
    let Some(points) = data.curve_points.get(&curve_id.to_string()) else {
        return 0.0;
    };
    let Some((first_x, first_y)) = points.first() else {
        return 0.0;
    };
    let x = x as f64;
    if x <= *first_x {
        return *first_y;
    }
    for pair in points.windows(2) {
        let (previous_x, previous_y) = pair[0];
        let (next_x, next_y) = pair[1];
        if x < next_x {
            return previous_y + (x - previous_x) / (next_x - previous_x) * (next_y - previous_y);
        }
    }
    points.last().map(|(_, y)| *y).unwrap_or_default()
}

fn highest<'a, const N: usize>(
    ids: &[u32],
    values: &'a BTreeMap<String, [i64; N]>,
) -> Option<&'a [i64; N]> {
    ids.iter()
        .filter_map(|id| values.get(&id_key(*id)))
        .max_by_key(|value| value[0])
}

/// Decode a bonus list for one curated item. `timewalker_level` is the auction
/// modifier type 9 when present; ordinary listings use the current level cap.
pub fn decode(
    item: ItemId,
    bonus_ids: &[u32],
    timewalker_level: Option<u16>,
) -> Option<DecodedItem> {
    let data = data();
    let item_data = data.items.get(&id_key(item.get()))?;
    let player_level = i64::from(timewalker_level.unwrap_or(PLAYER_LEVEL_CAP as u16));
    let mut level = item_data.base_item_level;
    let mut era = item_data.squish_era;
    let mut era_adjust = BTreeMap::<i64, i64>::new();

    if let Some([_, set_level]) = highest(bonus_ids, &data.level_data.legacy_set) {
        level = *set_level;
    }
    if let Some([_, curve_id, player_max]) = highest(bonus_ids, &data.level_data.content_tuning) {
        let player = if *player_max == 0 {
            player_level
        } else {
            player_level.min(*player_max)
        };
        level = rounded(curve(data, *curve_id, player));
    }
    for amount in bonus_ids
        .iter()
        .filter_map(|id| data.level_data.legacy_adjust.get(&id_key(*id)))
    {
        level += amount;
    }
    if let Some([_, base_level, curve_id, offset, set_era]) =
        highest(bonus_ids, &data.level_data.item_scaling_set)
    {
        let base = if *base_level == 0 { level } else { *base_level };
        level = if *curve_id == 0 {
            *base_level
        } else {
            rounded(curve(data, *curve_id, base))
        } + offset;
        era = *set_era;
    }
    for [curve_id, base_level, set_era] in bonus_ids
        .iter()
        .filter_map(|id| data.level_data.era_curve_set.get(&id_key(*id)))
    {
        level = rounded(curve(
            data,
            *curve_id,
            if *base_level == 0 { level } else { *base_level },
        ));
        era = *set_era;
    }
    if let Some([_, base_level, curve_id, offset, set_era]) =
        highest(bonus_ids, &data.level_data.item_scaling_set_by_player)
    {
        let base = if *base_level == 0 {
            player_level
        } else {
            *base_level
        };
        level = if *curve_id == 0 {
            *base_level
        } else {
            rounded(curve(data, *curve_id, base))
        } + offset;
        era = *set_era;
    }
    for [amount, fallback, check_era] in bonus_ids
        .iter()
        .filter_map(|id| data.level_data.era_adjust.get(&id_key(*id)))
    {
        if *check_era > era {
            *era_adjust.entry(*check_era).or_default() += amount;
            // Upstream's documented compatibility correction for items whose
            // base record predates the first squish era.
            if era == 0 {
                *era_adjust.entry(2).or_default() += 4;
            }
        } else {
            level += if *check_era < era { fallback } else { amount };
        }
    }
    if let Some([_, amount]) = highest(bonus_ids, &data.level_data.adjust) {
        level += amount;
    }
    for squish in &data.squish_eras {
        if squish.id > era && !squish.curve.is_empty() {
            level = rounded(curve_points(&squish.curve, level));
        }
        level += era_adjust.get(&squish.id).copied().unwrap_or_default();
        if squish.target {
            break;
        }
    }

    let name_suffix = bonus_ids
        .iter()
        .filter_map(|id| data.suffixes.get(&id_key(*id)))
        .max_by_key(|(priority, _)| *priority)
        .and_then(|(_, name_id)| data.suffix_names.get(&name_id.to_string()))
        .cloned();
    let tertiary_stats = TertiaryStat::ALL
        .into_iter()
        .filter(|stat| {
            data.tertiary_stats
                .get(stat.key())
                .is_some_and(|ids| ids.iter().any(|id| bonus_ids.contains(id)))
        })
        .collect();

    Some(DecodedItem {
        item_level: level.max(1).try_into().unwrap_or(u16::MAX),
        name_suffix,
        tertiary_stats,
    })
}

fn curve_points(points: &[(f64, f64)], x: i64) -> f64 {
    let Some((first_x, first_y)) = points.first() else {
        return 0.0;
    };
    let x = x as f64;
    if x <= *first_x {
        return *first_y;
    }
    for pair in points.windows(2) {
        let (previous_x, previous_y) = pair[0];
        let (next_x, next_y) = pair[1];
        if x < next_x {
            return previous_y + (x - previous_x) / (next_x - previous_x) * (next_y - previous_y);
        }
    }
    points.last().map(|(_, y)| *y).unwrap_or_default()
}

/// Offline metadata for a curated item. This never invokes the Blizzard API.
pub fn metadata(item: ItemId) -> Option<ItemMetadata> {
    let item_data = data().items.get(&id_key(item.get()))?;
    Some(ItemMetadata {
        item,
        icon: item_data.icon.clone(),
        vendor_buy: item_data.vendor_buy.map(Copper),
        vendor_sell: item_data.vendor_sell.map(Copper),
        stack_size: item_data.stack_size,
        bind_on_pickup: item_data.bind_on_pickup,
        expansion: item_data.expansion,
    })
}
