#!/usr/bin/env python3
"""Rebuild locales/messages.pot from the source.

Two sources, because a string can reach a visitor two ways:

  * `{{ "Raid consumables"|t }}` in an Askama template.
  * `EXTERNAL_STRINGS` in crates/app-web/src/i18n.rs, for the labels that come
    from other crates (`{{ node.status|t }}` shows a string this file never
    sees). A unit test keeps that list exhaustive.

The output is a plain gettext POT, which is what Weblate, Crowdin and
Transifex all read. Existing translations are never touched: run this, then let
the platform merge the new template into each PO.
"""

import pathlib
import re
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
TEMPLATES = ROOT / "crates/app-web/templates"
I18N_RS = ROOT / "crates/app-web/src/i18n.rs"
OUT = ROOT / "locales/messages.pot"

# `{{ "text"|t }}` and `{{ "text"|t|fill(x) }}`; the string may contain escaped
# quotes but not a bare one, which is what the template syntax allows anyway.
TEMPLATE_STRING = re.compile(r'"((?:[^"\\]|\\.)*)"\s*\|\s*t\b')


def template_strings() -> dict[str, list[str]]:
    found: dict[str, list[str]] = {}
    for path in sorted(TEMPLATES.rglob("*.html")):
        rel = path.relative_to(ROOT)
        for line_no, line in enumerate(path.read_text().splitlines(), 1):
            for match in TEMPLATE_STRING.finditer(line):
                found.setdefault(unescape(match.group(1)), []).append(f"{rel}:{line_no}")
    return found


def external_strings() -> dict[str, list[str]]:
    body = I18N_RS.read_text()
    block = body.split("pub const EXTERNAL_STRINGS", 1)[1].split("];", 1)[0]
    rel = I18N_RS.relative_to(ROOT)
    return {
        unescape(m.group(1)): [f"{rel}"]
        for m in re.finditer(r'"((?:[^"\\]|\\.)*)"', block)
    }


def unescape(raw: str) -> str:
    return raw.replace('\\"', '"').replace("\\\\", "\\")


def escape(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def read_po(body):
    """Parse a PO file into {msgid: msgstr}.

    Handles continuation lines, which is the whole point: gettext wraps long
    entries across several quoted lines, and so does every platform that round
    trips these files. A line-at-a-time regex reads such an entry as
    untranslated and reports coverage that is quietly, alarmingly wrong.
    """
    entries = {}
    msgid = msgstr = None
    target = None
    for line in body.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("msgid "):
            if msgid is not None and msgstr is not None:
                entries[msgid] = msgstr
            msgid, msgstr = unquote_po(line[6:]), None
            target = "msgid"
        elif line.startswith("msgstr "):
            msgstr = unquote_po(line[7:])
            target = "msgstr"
        elif line.startswith('"'):
            if target == "msgid":
                msgid += unquote_po(line)
            elif target == "msgstr":
                msgstr += unquote_po(line)
    if msgid is not None and msgstr is not None:
        entries[msgid] = msgstr
    return entries


def unquote_po(text):
    """The contents of one quoted PO string, with escapes resolved."""
    inner = re.findall(r'"((?:[^"\\]|\\.)*)"', text)
    return "".join(inner).replace('\\"', '"').replace("\\n", "\n").replace("\\\\", "\\")


def main() -> int:
    strings = template_strings()
    for msgid, refs in external_strings().items():
        strings.setdefault(msgid, []).extend(refs)

    version = subprocess.run(
        ["git", "describe", "--always", "--dirty"],
        capture_output=True, text=True, cwd=ROOT,
    ).stdout.strip() or "unknown"

    out = [
        "# Interface strings for Gavel.",
        "# Generated by scripts/i18n-extract.py -- do not edit by hand.",
        "#",
        "# The msgid is the English source string, so an untranslated entry",
        "# renders as English rather than as a missing key.",
        'msgid ""',
        'msgstr ""',
        f'"Project-Id-Version: gavel {version}\\n"',
        '"MIME-Version: 1.0\\n"',
        '"Content-Type: text/plain; charset=UTF-8\\n"',
        '"Content-Transfer-Encoding: 8bit\\n"',
        "",
    ]
    for msgid in sorted(strings):
        for ref in sorted(set(strings[msgid])):
            out.append(f"#: {ref}")
        out.append(f'msgid "{escape(msgid)}"')
        out.append('msgstr ""')
        out.append("")

    OUT.write_text("\n".join(out))
    print(f"{OUT.relative_to(ROOT)}: {len(strings)} strings")

    # Coverage per language, so an incomplete catalogue is visible here rather
    # than as an English sentence in the middle of a translated page.
    for po in sorted((ROOT / "locales").glob("*.po")):
        entries = read_po(po.read_text())
        done = sum(1 for msgid in strings if entries.get(msgid))
        print(f"{po.name}: {done}/{len(strings)} translated ({done * 100 // max(len(strings), 1)}%)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
