//! Compiles the PO catalogues into static string tables.
//!
//! Done at build time on purpose. The alternative -- parsing `.po` or `.mo`
//! files at startup -- would mean a runtime parser, a filesystem and an
//! allocation per string on a target that eventually has none of the three.
//! What lands in the binary is a sorted `&[(&str, &str)]` per language, looked
//! up with a binary search.
//!
//! The source language is English and the msgid *is* the English string, which
//! is the ordinary gettext convention: an untranslated string renders as
//! itself rather than as a missing key.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};
use std::{env, fs};

fn main() {
    let root = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap())
        .join("../..")
        .join("locales");
    println!("cargo:rerun-if-changed={}", root.display());
    println!(
        "cargo:rerun-if-changed={}",
        root.join("messages.pot").display()
    );

    let mut catalogs: Vec<(String, BTreeMap<String, String>)> = Vec::new();
    if let Ok(entries) = fs::read_dir(&root) {
        let mut files: Vec<PathBuf> = entries
            .filter_map(|e| e.ok().map(|e| e.path()))
            .filter(|p| p.extension().is_some_and(|e| e == "po"))
            .collect();
        files.sort();
        for path in files {
            println!("cargo:rerun-if-changed={}", path.display());
            let language = path.file_stem().unwrap().to_string_lossy().to_string();
            catalogs.push((language, parse_po(&path)));
        }
    }

    // How many strings there are to translate, so the running app can tell a
    // finished catalogue from one somebody has just started.
    let template = parse_po(&root.join("messages.pot"));
    let total = template.len().max(1);

    let mut out = String::from("// Generated by build.rs from locales/*.po. Do not edit.\n");
    out.push_str(&format!("pub const TOTAL_STRINGS: usize = {total};\n"));
    out.push_str("pub static CATALOGS: &[(&str, &[(&str, &str)])] = &[\n");
    for (language, entries) in &catalogs {
        out.push_str(&format!("    (\"{language}\", &[\n"));
        for (msgid, msgstr) in entries {
            if msgstr.is_empty() {
                continue; // untranslated: fall through to the English source
            }
            out.push_str(&format!("        ({}, {}),\n", quote(msgid), quote(msgstr)));
        }
        out.push_str("    ]),\n");
    }
    out.push_str("];\n");

    let dest = PathBuf::from(env::var("OUT_DIR").unwrap()).join("catalogs.rs");
    fs::write(dest, out).expect("writing the generated catalogues");
}

/// Minimal PO reader: `msgid` / `msgstr`, with continuation lines.
///
/// Deliberately not a full gettext implementation. Plurals and contexts are
/// not used by this application, and a translation platform never emits them
/// unless the source asks for them.
fn parse_po(path: &Path) -> BTreeMap<String, String> {
    // A missing template is not fatal: it only means the coverage figure has
    // nothing to compare against.
    let Ok(body) = fs::read_to_string(path) else {
        return BTreeMap::new();
    };
    let mut entries = BTreeMap::new();
    let mut msgid: Option<String> = None;
    let mut msgstr: Option<String> = None;
    // Which of the two the continuation lines belong to.
    let mut in_msgstr = false;

    let mut flush = |msgid: &mut Option<String>, msgstr: &mut Option<String>| {
        if let (Some(id), Some(text)) = (msgid.take(), msgstr.take())
            && !id.is_empty()
        {
            entries.insert(id, text);
        }
    };

    for line in body.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        if let Some(rest) = line.strip_prefix("msgid ") {
            flush(&mut msgid, &mut msgstr);
            msgid = Some(unquote(rest));
            in_msgstr = false;
        } else if let Some(rest) = line.strip_prefix("msgstr ") {
            msgstr = Some(unquote(rest));
            in_msgstr = true;
        } else if line.starts_with('"') {
            let piece = unquote(line);
            let target = if in_msgstr { &mut msgstr } else { &mut msgid };
            if let Some(existing) = target.as_mut() {
                existing.push_str(&piece);
            }
        }
    }
    flush(&mut msgid, &mut msgstr);
    entries
}

fn unquote(raw: &str) -> String {
    let raw = raw.trim();
    let inner = raw
        .strip_prefix('"')
        .and_then(|r| r.strip_suffix('"'))
        .unwrap_or(raw);
    let mut out = String::with_capacity(inner.len());
    let mut chars = inner.chars();
    while let Some(c) = chars.next() {
        if c != '\\' {
            out.push(c);
            continue;
        }
        match chars.next() {
            Some('n') => out.push('\n'),
            Some('t') => out.push('\t'),
            Some('"') => out.push('"'),
            Some('\\') => out.push('\\'),
            Some(other) => out.push(other),
            None => {}
        }
    }
    out
}

fn quote(value: &str) -> String {
    format!("{value:?}")
}
